# Generated by Django 3.1.5 on 2021-02-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210128_1831'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Executive',
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
