# Generated by Django 3.1.5 on 2021-02-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210210_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executive',
            name='about',
        ),
        migrations.AlterField(
            model_name='executive',
            name='image',
            field=models.ImageField(default='user-image.jpg', upload_to='images'),
        ),
    ]
