# Generated by Django 3.1.5 on 2021-02-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210210_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/event_images/%d-%m-%y/'),
        ),
    ]
